apiVersion: v1
kind: Pod
metadata:
  name: nginx-tolerated
  labels:
    env: test
spec:
  containers:
  - name: nginx
    image: nginx
  # Asking for VIP room
  nodeSelector:
    project: roboshop
  # Showing Booking Confirmation
  tolerations:
  - key: "project"
    operator: "Equal"
    value: "roboshop"
    effect: "NoExecute"